#!/bin/sh
#
# Copyright (c) 2022 Alexander Möller <alexander.moeller@fu-berlin.de>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

_fail='\033[31m' # red
_rset='\033[0m'  # reset colour

_force=0

_os=$(uname -s)
if [ "${_os}" = "Linux" ] ; then
	_top="home"
elif [ "${_os}" = "Darwin" ] ; then
	_top="Users"
fi

find_open() {
	printf "${_fail}===> Partially open home directories:${_rset}\n"
	printf "${_fail}---> group readable:${_rset}\n"
	ls -lA /"${_top}"/ | grep '^drwxr'
	printf "${_fail}---> group writeable:${_rset}\n"
	ls -lA /"${_top}"/ | grep '^drwx.w'
	printf "${_fail}---> globally readable:${_rset}\n"
	ls -lA /"${_top}"/ | grep '^drwx....w'
	printf "${_fail}---> globally writeable:${_rset}\n"
	ls -lA /"${_top}"/ | grep '^drwx....w'
}

usage() { cat << USAGE
${0##*/} - find home dirs that are r/w for not just its user
usage: ${0##*/} [-f]
USAGE
	exit 1
}

while getopts f arg ; do
	case ${arg} in
		f) _force=1 ;;
		*) usage
	esac
done
shift $((OPTIND - 1))

if [ "${_force}" -eq 1 ] ; then
	find_open
elif [ "$(dnsdomainname)" = "physik.fu-berlin.de" ] ; then
	find_open
else
	printf "You\'re outside the FUB-Physik network. You may force with -f\n"
	exit 1
fi
