#!/bin/sh
#
# Copyright (c) 2022 Alexander Möller <alexander.moeller@fu-berlin.de>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

_fail='\033[31m' # red
_rset='\033[0m'  # reset colour

find_unprotected() {
	printf "${_fail}===> Unprotected home directories:${_rset}\n"
	printf "${_fail}---> group screwable:${_rset}\n"
	ls -lA /home/ | grep -e '^drwxr' -e '^drwx.w'
	printf "${_fail}---> globally screwable:${_rset}\n"
	ls -lA /home/ | grep -e '^drwx...r' -e '^drwx....w'
}

if [ "$(dnsdomainname)" = "physik.fu-berlin.de" ] ; then
	find_unprotected
fi
