#!/bin/sh
#
# Copyright (c) 2022-2023 Alexander Möller <alexander.moeller@fu-berlin.de>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

AGKOCHDIR=${AGKOCHDIR:-${HOME}/Cloud/fubox/AG\ Koch}
FUBOXDIR=${FUBOXDIR:-${HOME}/Cloud/fubox}

_fail='\033[31m' # red
_good='\033[32m' # green
_rset='\033[0m'  # reset colour

find_weird() {
	printf "===> Files & directories containing weird characters:\n"
	find "${AGKOCHDIR}" \
		-iname '* *' \
		-o -iname '*ö*' \
		-o -iname '*ä*' \
		-o -iname '*ü*' \
		-o -iname '*\(*' \
		-o -iname '*\)*' \
		-o -iname '*\[*' \
		-o -iname '*\]*' \
		-o -iname '*\{*' \
		-o -iname '*\}*' \
		-o -iname '*\&*' \
		-o -iname '*ß*' \
		| awk -v rootdir="${FUBOXDIR}/" -v found="${_fail}" -v reset="${_rset}" '{ gsub(rootdir, "", $0); print found$0reset }'

	_readmefiles=$(find "${AGKOCHDIR}" -name 'Readme.md')
	printf "\n===> Readme.md files and their contents:\n"
	if [ -n "${_readmefiles}" ] ; then
		IFS='
		'
		for f in ${_readmefiles}
		do
			printf "\n${_fail}---> %s${_rset}" "$f"
			printf "\n---> %s\n" "$(cat $f)"
		done
	else
		printf "${_good}No Readme.md found.${_rset}\n"
	fi
}

find_weird
