#!/bin/sh

AGKOCHDIR=${AGKOCHDIR:-${HOME}/Cloud/fubox/AG\ Koch/}
FUBOXDIR=${FUBOXDIR:-${HOME}/Cloud/fubox/}

find_weird() {
	printf "\n===> Files & directories containing weird characters:\n"
	find "${AGKOCHDIR}" \
		-iname '* *' \
		-o -iname '*ö*' \
		-o -iname '*ä*' \
		-o -iname '*ü*' \
		-o -iname '*\(*' \
		-o -iname '*\)*' \
		-o -iname '*\[*' \
		-o -iname '*\]*' \
		-o -iname '*\{*' \
		-o -iname '*\}*' \
		-o -iname '*\&*' \
		-o -iname '*ß*' \
		| awk -v rootdir="${FUBOXDIR}/" '{ gsub(rootdir, "", $0); print $0 }'

	printf "\n===> Readme.md files and their contents\n"
	IFS='
	'
	_readmefiles=$(find "${AGKOCHDIR}" -name 'Readme.md')
	for f in ${_readmefiles}
	do
		printf "\n\033[31m---> %s\033[0m" "$f"
		printf "\n---> %s\n" "$(cat $f)"
	done
}

find_weird
