#!/bin/sh

_agkochdir="$HOME"/Cloud/fubox/AG\ Koch
_fuboxdir="$HOME"/Cloud/fubox

find_weird() {
	printf "\n===> Files & directories containing weird characters:\n"
	find "${_agkochdir}" \
		-iname '* *' \
		-o -iname '*ö*' \
		-o -iname '*ä*' \
		-o -iname '*ü*' \
		-o -iname '*\(*' \
		-o -iname '*\)*' \
		-o -iname '*\[*' \
		-o -iname '*\]*' \
		-o -iname '*\{*' \
		-o -iname '*\}*' \
		-o -iname '*\&*' \
		-o -iname '*ß*' \
		| awk -v rootdir="${_fuboxdir}/" '{ gsub(rootdir, "", $0); print $0 }'

	printf "\n===> Readme.md files and their contents\n"
	IFS='
	'
	_readmefiles=$(find "${_agkochdir}" -name 'Readme.md')
	for f in ${_readmefiles}
	do
		printf "\n\033[31m---> %s\033[0m" "$f"
		printf "\n---> %s\n" "$(cat $f)"
	done
}

find_weird
